Map<String, Object[][]> toSheetNameArrayMap(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayMap(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetNameArrayInvertedMap(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayInvertedMap(Map<String, Compression.ZipEntry> entries, Set<String> selectedSheets){}


String toLlmText(Map<String,Compression.ZipEntry> entries){}
String toLlmText(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}


// Todo
Map<String, Object[][]> toSheetNameArrayMapDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayMapDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetNameArrayMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
