Map<String, Object[][]> toSheetNameArrayMap(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayMap(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetNameArrayInvertedMap(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetNameArrayInvertedMap(Map<String, Compression.ZipEntry> entries, Set<String> selectedSheets){}





Map<String, Object[][]> toSheetMapDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMapDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
