Map<String, Object[][]> toSheetMap(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMap(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetMapDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMapDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetMapInverted(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMapInverted(Map<String, Compression.ZipEntry> entries, Set<String> selectedSheets){}
Map<String, Object[][]> toSheetMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries){}
Map<String, Object[][]> toSheetMapInvertedDomDoc(Map<String,Compression.ZipEntry> entries, Set<String> selectedSheets){}
